### ISSUE TITLE
Fatal error: Uncaught Exception: Unexpected Camelot error

### ISSUE THREAD

**Issue by dot4all** [randomstate/camelot-php#2]
Hi,
I have a problem using wrapper: RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps. This system lists a couple of UTF-8 supporting locales that you can pick from. Can someone help me?
Thanks a lot

**Comment by byfoz** [comment]
Hi @dot4all ,

That issue is unrelated to this library I'm afraid.
If you go to the link you referenced and scroll to the appropriate section (linked here: https://click.palletsprojects.com/en/7.x/python3/#python-3-surrogate-handling) you can see a very clear message telling you what next steps you need to perform to resolve it.

This is a PHP-only library so any python related errors are likely to be related to your environment and would be better asked on stack overflow or in a python-specific community.

<img width="902" alt="image" src="https://user-images.githubusercontent.com/3436576/82645248-7e40bf80-9c0a-11ea-8515-8a1bef8ec695.png">
